

##
# Class which contains all the constant values used by the system
#
class Constants:
    STARTUP_TIME = 200  # time needed to initialize the system
    MAX_SIMULATION_TIME = 800  # total simulation time
    NUMBER_OF_RUNS = 5  # number of times that the simulation will be run
    STATIONS_NUM = 4  # number of stations in the system
    JOB_TYPES_NUM = 4  # number of different job types
    AVG_WORKER_UTIL_INTERVAL_ACCURACY = 0.975  # accuracy for average workers utilizations confidence intervals
    JOB_RESPONSE_TIME_INTERVAL_ACCURACY_EX13 = 0.95  # accuracy for mean total response time confidence intervals
    JOB_RESPONSE_TIME_INTERVAL_ACCURACY_EX14 = 0.975  # accuracy for mean total response time confidence intervals

    DEBUG_MODE = True  # if True, log will be verbose
    JOB_COMPARATOR = None  # FIFOComparator() or ByTypeComparator()

    SEED = 12345  # None # seed of the random number generator
    STATION_QUEUE_SIZE = 0  # size of the stations' queue (0 == infinite queue size)
    ARRIVAL_RATE = 4  # mean for the arrival rate
    FIRST_STATIONS = {1: 1, 2: 1, 3: 2, 4: 1}  # key: job type; value: starting station

    # stations' service time probability distribution parameters
    STATION1_DISTRIBUTIONS = {1: (20, 3), 2: (18, 2), 3: None, 4: (30, 5)}
    STATION2_DISTRIBUTIONS = {1: (30, 5), 2: None, 3: (20, 2), 4: None}
    STATION3_DISTRIBUTIONS = {1: (75, 4), 2: (60, 5), 3: (50, 8), 4: None}
    STATION4_DISTRIBUTIONS = {1: (20, 3), 2: (10, 1), 3: (10, 1), 4: (15, 2)}

    # number of workers for each station
    STATION1_CAPACITY = 8
    STATION2_CAPACITY = 8
    STATION3_CAPACITY = 20
    STATION4_CAPACITY = 7

    # key: station's id; value: service time distribution
    STATIONS_DISTRIBUTIONS = {1: STATION1_DISTRIBUTIONS, 2: STATION2_DISTRIBUTIONS,
                              3: STATION3_DISTRIBUTIONS, 4: STATION4_DISTRIBUTIONS}
    # key: station's id; value: station's capacity
    STATIONS_CAPACITY = {1: STATION1_CAPACITY, 2: STATION2_CAPACITY, 3: STATION3_CAPACITY, 4: STATION4_CAPACITY}

    # critical values for the Kolmogorov-Smirnov test
    KS_CRITICAL_VALUES = {
        1: {0.1: 0.950, 0.05: 0.975, 0.01: 0.995},
        2: {0.1: 0.776, 0.05: 0.842, 0.01: 0.929},
        3: {0.1: 0.642, 0.05: 0.708, 0.01: 0.828},
        4: {0.1: 0.564, 0.05: 0.624, 0.01: 0.733},
        5: {0.1: 0.510, 0.05: 0.565, 0.01: 0.669},
        6: {0.1: 0.470, 0.05: 0.521, 0.01: 0.618},
        7: {0.1: 0.438, 0.05: 0.486, 0.01: 0.577},
        8: {0.1: 0.411, 0.05: 0.457, 0.01: 0.543},
        9: {0.1: 0.388, 0.05: 0.432, 0.01: 0.514},
        10: {0.1: 0.368, 0.05: 0.410, 0.01: 0.490},
        11: {0.1: 0.352, 0.05: 0.391, 0.01: 0.468},
        12: {0.1: 0.338, 0.05: 0.375, 0.01: 0.450},
        13: {0.1: 0.325, 0.05: 0.361, 0.01: 0.433},
        14: {0.1: 0.314, 0.05: 0.349, 0.01: 0.418},
        15: {0.1: 0.304, 0.05: 0.338, 0.01: 0.404},
        16: {0.1: 0.295, 0.05: 0.328, 0.01: 0.392},
        17: {0.1: 0.286, 0.05: 0.318, 0.01: 0.381},
        18: {0.1: 0.278, 0.05: 0.309, 0.01: 0.371},
        19: {0.1: 0.272, 0.05: 0.301, 0.01: 0.363},
        20: {0.1: 0.264, 0.05: 0.294, 0.01: 0.356},
        21: {0.1: 0.259, 0.05: 0.287, 0.01: 0.344},
        22: {0.1: 0.253, 0.05: 0.281, 0.01: 0.337},
        23: {0.1: 0.247, 0.05: 0.275, 0.01: 0.330},
        24: {0.1: 0.242, 0.05: 0.269, 0.01: 0.323},
        25: {0.1: 0.240, 0.05: 0.270, 0.01: 0.320},
        26: {0.1: 0.233, 0.05: 0.259, 0.01: 0.311},
        27: {0.1: 0.229, 0.05: 0.254, 0.01: 0.305},
        28: {0.1: 0.225, 0.05: 0.250, 0.01: 0.300},
        29: {0.1: 0.221, 0.05: 0.246, 0.01: 0.295},
        30: {0.1: 0.220, 0.05: 0.240, 0.01: 0.290},
        31: {0.1: 0.214, 0.05: 0.238, 0.01: 0.285},
        32: {0.1: 0.211, 0.05: 0.234, 0.01: 0.281},
        33: {0.1: 0.208, 0.05: 0.231, 0.01: 0.277},
        34: {0.1: 0.205, 0.05: 0.227, 0.01: 0.273},
        35: {0.1: 0.210, 0.05: 0.230, 0.01: 0.270},
        'over': {0.10: 1.224, 0.05: 1.358, 0.01: 1.628}
    }

    # critical values for the chi-square test (for some degrees of freedom)
    CS_TEST_VALUES = {
        25: {0.1: 34.4, 0.05: 37.7, 0.025: 40.6, 0.01: 44.3, 0.005: 49.6},
        50: {0.1: 63.2, 0.05: 67.5, 0.025: 71.4, 0.01: 76.2, 0.005: 79.5},
        100: {0.1: 118.5, 0.05: 124.3, 0.025: 129.6, 0.01: 135.8, 0.005: 140.2}
    }

    COLORS = {'BLUE': '\033[94m',
              'PINK': '\033[95m',
              'GREEN': '\033[92m',
              'YELLOW': '\033[93m',
              'RED': '\033[91m'}

    FIGURE_WIDTH = 13  # width of the figure generated by Matplotlib
    FIGURE_HEIGHT = 8  # width of the figure generated by Matplotlib
