Performance Study of a Job Shop System: jobshop.statistics.OutputAnalysis Namespace Reference
jobshop.statistics.OutputAnalysis Namespace Reference
Functions
def run
Generates statistics about a specific exercise using the data collected during the simulation.
def avg_worker_utilization
Computes the average worker utilization for a specific station distributed among the different executions of the simulation.
def mean_total_response_time
Computes the mean total response time for a specific type of job that is satisfied by the jobshop's workers.
def confidence_interval
Generates the confidence interval starting from the data in input and using a specific degree of accuracy specified by the user.
Function Documentation
def jobshop.statistics.OutputAnalysis.avg_worker_utilization (stations_list_runs, curr_station_index)
Computes the average worker utilization for a specific station distributed among the different executions of the simulation.
A confidence interval is generated at the end of the function using a specific significance value which is defined by the exercise.
Parameters
stations_list_runs a list of Station objects for each run
curr_station_index the station for which will be computed the metric
Returns
a string representation of the confidence interval for this metric
Definition at line 40 of file OutputAnalysis.py.
References jobshop.statistics.OutputAnalysis.confidence_interval().
def jobshop.statistics.OutputAnalysis.confidence_interval (values, accuracy)
Generates the confidence interval starting from the data in input and using a specific degree of accuracy specified by the user.
This kind of statistical test is used in order to compute output analysis on the results obtained from the simulation.
Parameters
values reference values for the test
accuracy significance value for the current test
Returns
a string representation of the confidence interval computed
Definition at line 81 of file OutputAnalysis.py.
def jobshop.statistics.OutputAnalysis.mean_total_response_time (jobs_list_runs, job_type_index, accuracy)
Computes the mean total response time for a specific type of job that is satisfied by the jobshop's workers.
A confidence interval is generated at the end of the function using a specific significance value which is defined by the exercise.
Parameters
jobs_list_runs list of jobs executed for each run
job_type_index job type's index for which we want to compute the metric
accuracy the significance level at which we want to compute the confidence interval
Returns
a string representation of the confidence interval computed
Definition at line 62 of file OutputAnalysis.py.
References jobshop.statistics.OutputAnalysis.confidence_interval().
def jobshop.statistics.OutputAnalysis.run (stats, exercise_num)
Generates statistics about a specific exercise using the data collected during the simulation.
Parameters
stats simulation data collected
exercise_num a string representation of the exercise that will be analyzed
Definition at line 12 of file OutputAnalysis.py.
References jobshop.statistics.OutputAnalysis.avg_worker_utilization(), and jobshop.statistics.OutputAnalysis.mean_total_response_time().